### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by hasufell** [liquidz/vim-iced#89]
```
$ iced repl
OK: Leiningen project is detected
Retrieving cider/piggieback/0.3.10/piggieback-0.3.10.pom from clojars
Retrieving nrepl/nrepl/0.4.4/nrepl-0.4.4.pom from clojars
Retrieving org/clojure/tools.logging/0.4.1/tools.logging-0.4.1.pom from central
Retrieving iced-nrepl/iced-nrepl/0.4.1/iced-nrepl-0.4.1.pom from clojars
Retrieving nrepl/nrepl/0.5.3/nrepl-0.5.3.pom from clojars
Retrieving nrepl/bencode/1.0.0/bencode-1.0.0.pom from clojars
Retrieving refactor-nrepl/refactor-nrepl/2.4.0/refactor-nrepl-2.4.0.pom from clojars
Retrieving cider/cider-nrepl/0.20.0/cider-nrepl-0.20.0.pom from clojars
Retrieving cider/orchard/0.4.0/orchard-0.4.0.pom from clojars
Retrieving org/tcrawley/dynapath/0.2.5/dynapath-0.2.5.pom from central
Retrieving org/clojure/java.classpath/0.3.0/java.classpath-0.3.0.pom from central
Retrieving org/clojure/tools.namespace/0.3.0-alpha4/tools.namespace-0.3.0-alpha4.pom from central
Retrieving thunknyc/profile/0.5.2/profile-0.5.2.pom from clojars
Retrieving mvxcvi/puget/1.0.2/puget-1.0.2.pom from clojars
Retrieving mvxcvi/arrangement/1.1.1/arrangement-1.1.1.pom from clojars
Retrieving fipp/fipp/0.6.10/fipp-0.6.10.pom from clojars
Retrieving fipp/fipp/0.6.14/fipp-0.6.14.pom from clojars
Retrieving org/clojure/core.rrb-vector/0.0.13/core.rrb-vector-0.0.13.pom from central
Retrieving compliment/compliment/0.3.8/compliment-0.3.8.pom from clojars
Retrieving cljs-tooling/cljs-tooling/0.3.1/cljs-tooling-0.3.1.pom from clojars
Retrieving cljfmt/cljfmt/0.6.1/cljfmt-0.6.1.pom from clojars
Retrieving org/clojure/tools.cli/0.3.7/tools.cli-0.3.7.pom from central
Retrieving org/clojure/tools.reader/1.2.2/tools.reader-1.2.2.pom from central
Retrieving com/googlecode/java-diff-utils/diffutils/1.3.0/diffutils-1.3.0.pom from central
Retrieving rewrite-clj/rewrite-clj/0.6.0/rewrite-clj-0.6.0.pom from clojars
Retrieving rewrite-cljs/rewrite-cljs/0.4.4/rewrite-cljs-0.4.4.pom from clojars
Retrieving org/clojure/tools.trace/0.7.10/tools.trace-0.7.10.pom from central
Retrieving org/tcrawley/dynapath/0.2.5/dynapath-0.2.5.jar from central
Retrieving org/clojure/core.rrb-vector/0.0.13/core.rrb-vector-0.0.13.jar from central
Retrieving com/googlecode/java-diff-utils/diffutils/1.3.0/diffutils-1.3.0.jar from central
Retrieving org/clojure/tools.cli/0.3.7/tools.cli-0.3.7.jar from central
Retrieving org/clojure/java.classpath/0.3.0/java.classpath-0.3.0.jar from central
Retrieving org/clojure/tools.reader/1.2.2/tools.reader-1.2.2.jar from central
Retrieving org/clojure/tools.namespace/0.3.0-alpha4/tools.namespace-0.3.0-alpha4.jar from central
Retrieving org/clojure/tools.trace/0.7.10/tools.trace-0.7.10.jar from central
Retrieving cider/cider-nrepl/0.20.0/cider-nrepl-0.20.0.jar from clojars
Retrieving thunknyc/profile/0.5.2/profile-0.5.2.jar from clojars
Retrieving cider/piggieback/0.3.10/piggieback-0.3.10.jar from clojars
Retrieving cider/orchard/0.4.0/orchard-0.4.0.jar from clojars
Retrieving iced-nrepl/iced-nrepl/0.4.1/iced-nrepl-0.4.1.jar from clojars
Retrieving mvxcvi/puget/1.0.2/puget-1.0.2.jar from clojars
Retrieving mvxcvi/arrangement/1.1.1/arrangement-1.1.1.jar from clojars
Retrieving fipp/fipp/0.6.14/fipp-0.6.14.jar from clojars
Retrieving compliment/compliment/0.3.8/compliment-0.3.8.jar from clojars
Retrieving cljs-tooling/cljs-tooling/0.3.1/cljs-tooling-0.3.1.jar from clojars
Retrieving cljfmt/cljfmt/0.6.1/cljfmt-0.6.1.jar from clojars
Retrieving rewrite-clj/rewrite-clj/0.6.0/rewrite-clj-0.6.0.jar from clojars
Retrieving rewrite-cljs/rewrite-cljs/0.4.4/rewrite-cljs-0.4.4.jar from clojars
Retrieving nrepl/nrepl/0.5.3/nrepl-0.5.3.jar from clojars
Retrieving nrepl/bencode/1.0.0/bencode-1.0.0.jar from clojars
Retrieving refactor-nrepl/refactor-nrepl/2.4.0/refactor-nrepl-2.4.0.jar from clojars
[WARNING] No nREPL middleware descriptor in metadata of #'cider.piggieback/wrap-cljs-repl, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.piggieback/wrap-cljs-repl, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.piggieback/wrap-cljs-repl, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.piggieback/wrap-cljs-repl, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.piggieback/wrap-cljs-repl, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.piggieback/wrap-cljs-repl, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.piggieback/wrap-cljs-repl, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.piggieback/wrap-cljs-repl, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.piggieback/wrap-cljs-repl, see nrepl.middleware/set-descriptor!
[WARNING] No nREPL middleware descriptor in metadata of #'cider.piggieback/wrap-cljs-repl, see nrepl.middleware/set-descriptor!
Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: cider.nrepl/wrap-pprint in this context, compiling:(/tmp/form-init8693096450787375708.clj:1:12169)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7010)
	at clojure.lang.Compiler.analyze(Compiler.java:6773)
	at clojure.lang.Compiler.analyze(Compiler.java:6729)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3881)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7005)
	at clojure.lang.Compiler.analyze(Compiler.java:6773)
	at clojure.lang.Compiler.analyze(Compiler.java:6729)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3881)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7005)
	at clojure.lang.Compiler.analyze(Compiler.java:6773)
	at clojure.lang.Compiler.access$300(Compiler.java:38)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6368)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7003)
	at clojure.lang.Compiler.analyze(Compiler.java:6773)
	at clojure.lang.Compiler.analyze(Compiler.java:6729)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6100)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5460)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:4022)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7001)
	at clojure.lang.Compiler.analyze(Compiler.java:6773)
	at clojure.lang.Compiler.eval(Compiler.java:7059)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invokeStatic(main.clj:311)
	at clojure.main$null_opt.invokeStatic(main.clj:345)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: Unable to resolve var: cider.nrepl/wrap-pprint in this context
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler$TheVarExpr$Parser.parse(Compiler.java:720)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7003)
	... 35 more
REPL server launch timed out.
```

**Comment by jahson** [comment]
Try to remove `wrap-pprint` and `wrap-pprint-fn` from the `:nrepl-middleware` vector.
```
cat ~/.lein/profiles.clj
{:user
 {:dependencies [[nrepl "0.5.3"]
                 [iced-nrepl "0.4.1"]
                 [cider/cider-nrepl "0.20.0"]]
  :repl-options {:nrepl-middleware [cider.nrepl/wrap-classpath
                                    cider.nrepl/wrap-complete
                                    cider.nrepl/wrap-debug
                                    cider.nrepl/wrap-format
                                    cider.nrepl/wrap-info
                                    cider.nrepl/wrap-macroexpand
                                    cider.nrepl/wrap-ns
                                    cider.nrepl/wrap-out
                                    cider.nrepl/wrap-spec
                                    cider.nrepl/wrap-test
                                    cider.nrepl/wrap-trace
                                    cider.nrepl/wrap-undef
                                    iced.nrepl/wrap-iced]}
  :plugins [[refactor-nrepl "2.4.0"]]}}
```
The reason is they are deprecated
https://github.com/clojure-emacs/cider-nrepl/blob/7bfb2a4a5ec5f517b054b45e1bc805f6df09eda6/README.md#supplied-nrepl-middleware

**Comment by hasufell** [comment]
That seems to work, but it isn't documented anywhere here.

**Comment by liquidz** [comment]
@hasufell Oh, I forgot to remove these lines from document.
https://github.com/liquidz/vim-iced/blob/0.9.3/doc/vim-iced.txt#L107
https://github.com/liquidz/vim-iced/commit/85ee9722663ad5660c2f0172a9892960e35d5d80#diff-7d0896ed5ea1c6fc26e5cbcf9d08cf4c
I'll fix documents!

@jahson Thanks for your helping!

**Comment by hasufell** [comment]
Even after this, basically nothing works.

Evaluating namespace does something like: `Session error. You should be in cljs session`.

**Comment by liquidz** [comment]
@hasufell You need to start cljs repl if you are editing *.cljs file.

Could you try to start cljs repl?
https://github.com/liquidz/vim-iced/blob/0.9.3/doc/vim-iced.txt#L200

**Comment by hasufell** [comment]
And next error...

![screenshot_2019-02-11_00-38-17](https://user-images.githubusercontent.com/1241845/52536435-72264b00-2d95-11e9-9663-2f7c77cb693b.png)

**Comment by liquidz** [comment]
@hasufell What cljs environment do you use?
If figwheel, figwheel requires websocket communication between figwheel and browser.

So you need to access a page which includes figwheel generated JS via browser.
This is a behavior of figwheel, not vim-iced.

**Comment by hasufell** [comment]
> So you need to access a page which includes figwheel generated JS via browser.
> This is a behavior of figwheel, not vim-iced.

I already have. But changing source files does nothing.

In addition I get this error in iced repl when I do `:IcedDisconnect`:

```
user=> ERROR: Unhandled REPL handler exception processing message {:session abe1fd69-a5c8-41c5-b173-5f14c35d6db6, :print-level 10, :print-length 10, :op init-debugger}
java.lang.IllegalArgumentException: No implementation of method: :send of protocol: #'nrepl.transport/Transport found for class: clojure.tools.nrepl.transport.FnTransport
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
	at nrepl.transport$eval19469$fn__19470$G__19460__19477.invoke(transport.clj:16)
	at cider.nrepl.middleware.debug$debugger_send.invokeStatic(debug.clj:200)
	at cider.nrepl.middleware.debug$debugger_send.doInvoke(debug.clj:194)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at cider.nrepl.middleware.debug$initialize.invokeStatic(debug.clj:625)
	at cider.nrepl.middleware.debug$initialize.invoke(debug.clj:621)
	at cider.nrepl.middleware.debug$handle_debug.invokeStatic(debug.clj:649)
	at cider.nrepl.middleware.debug$handle_debug.invoke(debug.clj:640)
	at clojure.lang.Var.invoke(Var.java:385)
	at cider.nrepl$wrap_debug$fn__20384.invoke(nrepl.clj:160)
	at nrepl.middleware$wrap_conj_descriptor$fn__19624.invoke(middleware.clj:17)
	at cider.nrepl$wrap_undef$fn__20514.invoke(nrepl.clj:468)
	at nrepl.middleware$wrap_conj_descriptor$fn__19624.invoke(middleware.clj:17)
	at cider.nrepl$wrap_spec$fn__20474.invoke(nrepl.clj:393)
	at nrepl.middleware$wrap_conj_descriptor$fn__19624.invoke(middleware.clj:17)
	at cider.nrepl$wrap_test$fn__20490.invoke(nrepl.clj:419)
	at nrepl.middleware$wrap_conj_descriptor$fn__19624.invoke(middleware.clj:17)
	at cider.nrepl$wrap_trace$fn__20498.invoke(nrepl.clj:439)
	at nrepl.middleware$wrap_conj_descriptor$fn__19624.invoke(middleware.clj:17)
	at cider.nrepl$wrap_ns$fn__20434.invoke(nrepl.clj:277)
	at nrepl.middleware$wrap_conj_descriptor$fn__19624.invoke(middleware.clj:17)
	at cider.nrepl$wrap_macroexpand$fn__20426.invoke(nrepl.clj:264)
	at nrepl.middleware$wrap_conj_descriptor$fn__19624.invoke(middleware.clj:17)
	at cider.nrepl$wrap_out$fn__20442.invoke(nrepl.clj:309)
	at nrepl.middleware$wrap_conj_descriptor$fn__19624.invoke(middleware.clj:17)
	at cider.nrepl$wrap_classpath$fn__20366.invoke(nrepl.clj:134)
	at nrepl.middleware$wrap_conj_descriptor$fn__19624.invoke(middleware.clj:17)
	at cider.nrepl$wrap_complete$fn__20374.invoke(nrepl.clj:140)
	at nrepl.middleware$wrap_conj_descriptor$fn__19624.invoke(middleware.clj:17)
	at clojure.tools.nrepl.server$handle_STAR_.invokeStatic(server.clj:19)
	at clojure.tools.nrepl.server$handle_STAR_.invoke(server.clj:16)
	at clojure.tools.nrepl.server$handle$fn__1004.invoke(server.clj:28)
	at clojure.core$binding_conveyor_fn$fn__5476.invoke(core.clj:2022)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Running `:IcedStartCljsRepl` I get:

```
user=> ERROR: Unhandled REPL handler exception processing message {:session abe1fd69-a5c8-41c5-b173-5f14c35d6db6, :op classpath}
java.lang.IllegalArgumentException: No implementation of method: :send of protocol: #'nrepl.transport/Transport found for class: clojure.tools.nrepl.transport.FnTransport
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
	at nrepl.transport$eval19469$fn__19470$G__19460__19477.invoke(transport.clj:16)
	at cider.nrepl.middleware.classpath$handle_classpath.invokeStatic(classpath.clj:10)
	at cider.nrepl.middleware.classpath$handle_classpath.invoke(classpath.clj:9)
	at clojure.lang.Var.invoke(Var.java:385)
	at cider.nrepl$wrap_classpath$fn__20366.invoke(nrepl.clj:134)
	at nrepl.middleware$wrap_conj_descriptor$fn__19624.invoke(middleware.clj:17)
	at cider.nrepl$wrap_complete$fn__20374.invoke(nrepl.clj:140)
	at nrepl.middleware$wrap_conj_descriptor$fn__19624.invoke(middleware.clj:17)
	at clojure.tools.nrepl.server$handle_STAR_.invokeStatic(server.clj:19)
	at clojure.tools.nrepl.server$handle_STAR_.invoke(server.clj:16)
	at clojure.tools.nrepl.server$handle$fn__1004.invoke(server.clj:28)
	at clojure.core$binding_conveyor_fn$fn__5476.invoke(core.clj:2022)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

and the above error in vim.

**Comment by hasufell** [comment]
>  If figwheel, figwheel requires websocket communication between figwheel and browser.

Yes, the project uses figwheel.

**Comment by hasufell** [comment]
I also tried Clojure CLI, doesn't work either with clojurescript:

```
Connected.
class java.io.FileNotFoundException
FileNotFoundException Could not locate figwheel_sidecar/repl_api__init.class or figwheel_sidecar/repl_api.clj on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.  clojure.lang.RT.load (RT.java:463)
```

**Comment by liquidz** [comment]
> java.lang.IllegalArgumentException: No implementation of method: :send of protocol: #'nrepl.transport/Transport found for class: clojure.tools.nrepl.transport.FnTransport

@hasufell It seems that your nrepl version is outdate.
Latest leiningen does not use clojure.tools.nrepl.
Could you upgrade leiningen?

https://github.com/technomancy/leiningen/blob/master/NEWS.md#282--2018-12-11

> I also tried Clojure CLI, doesn't work either with clojurescript:

Could you provide your deps.edn?

**Comment by hasufell** [comment]
> Could you provide your deps.edn?

```
{:deps {bidi {:mvn/version "2.1.4"}
        cljsjs/create-react-class {:mvn/version "15.6.3-0"}
        cljsjs/csv {:mvn/version "1.1.1-0"}
        cljsjs/react {:mvn/version "16.0.0-0"}
        cljsjs/react-dom {:mvn/version "16.0.0-0"}
        com.andrewmcveigh/cljs-time {:mvn/version "0.5.2"}
        com.bhauman/figwheel-main {:mvn/version "0.2.0"}
        com.bhauman/rebel-readline-cljs {:mvn/version "0.1.4"}
        org.clojure/clojure {:mvn/version "1.9.0"}
        org.clojure/clojurescript {:mvn/version "1.10.339"}
        org.clojure/core.async {:mvn/version "0.4.474"}
        org.omcljs/om {:mvn/version "1.0.0-beta4"}
        prismatic/dommy {:mvn/version "1.1.0"}
        venantius/accountant {:mvn/version "0.2.4"}}
 :aliases {:fig {:main-opts ["-m" "figwheel.main"]}
           :cljs {:main-opts ["-m" "cljs.main"]}}
 :paths ["lib" "main" "../.."]}
```

**Comment by hasufell** [comment]
> Could you upgrade leiningen?

Did that. Just get different errors:

```
Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: cider.piggieback/wrap-cljs-repl in this context, compiling:(/tmp/form-init505388911630847116.clj:1:9840)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7010)
	at clojure.lang.Compiler.analyze(Compiler.java:6773)
	at clojure.lang.Compiler.analyze(Compiler.java:6729)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3881)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7005)
	at clojure.lang.Compiler.analyze(Compiler.java:6773)
	at clojure.lang.Compiler.analyze(Compiler.java:6729)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3881)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7005)
	at clojure.lang.Compiler.analyze(Compiler.java:6773)
	at clojure.lang.Compiler.access$300(Compiler.java:38)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6368)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7003)
	at clojure.lang.Compiler.analyze(Compiler.java:6773)
	at clojure.lang.Compiler.analyze(Compiler.java:6729)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6100)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5460)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:4022)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7001)
	at clojure.lang.Compiler.analyze(Compiler.java:6773)
	at clojure.lang.Compiler.eval(Compiler.java:7059)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invokeStatic(main.clj:311)
	at clojure.main$null_opt.invokeStatic(main.clj:345)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: Unable to resolve var: cider.piggieback/wrap-cljs-repl in this context
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler$TheVarExpr$Parser.parse(Compiler.java:720)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7003)
	... 36 more
```

Clojure tooling is seriously an entire mess. I already had these kind of things when trying other tools. It's pretty much all the same, which is sad.

**Comment by liquidz** [comment]
@hasufell I had not test with figwheel.main yet.
I'll test it.

> Unable to resolve var: cider.piggieback/wrap-cljs-repl

Did you launch repl with --with-cljs option?
https://github.com/liquidz/vim-iced/blob/0.9.3/doc/vim-iced.txt#L226

> Clojure tooling is seriously an entire mess. I already had these kind of things when trying other tools. It's pretty much all the same, which is sad.

To improve clojure tooling, pull requests welcome!!

**Comment by hasufell** [comment]
> Did you launch repl with --with-cljs option?

Yes I did.

**Comment by hasufell** [comment]
> Could you provide your deps.edn?

https://github.com/liquidz/vim-iced/blob/master/bin/iced#L133 so this is missing figwheel-sidecar

**Comment by hasufell** [comment]
> https://github.com/liquidz/vim-iced/blob/master/bin/iced#L133 so this is missing figwheel-sidecar

Fixing that it *seems* to start, but then fails at evaluating anything:

```
Session error. You should be in cljs session.
```

I give up lol.

**Comment by liquidz** [comment]
@hasufell Hmm, I have no idea about this error excepting --with-cljs option.
I'll test it more.
If you have minimal step to reproduce this error, please provide it.

> so this is missing figwheel-sidecar

figwheel-sidecar is not always necessary such as nashorn or graaljs environment.
So I did not add it on purpose.

**Comment by hasufell** [comment]
>  If you have minimal step to reproduce this error, please provide it.

I don't. The codebase is 18k LOC and not open source. I tried many other different editor plugins, basically none of them work, only some emacs ones.

Thanks for the help though.
